### ISSUE TITLE
Place spare pieces

### ISSUE THREAD

**Issue by ChinYouHng** [lengyanyu258/xiangqiboardjs#11]
Hi! I have integrated with xiangqi.js and the spare pieces cannot be placed on the board anymore, how can i enable it?

**Comment by lengyanyu258** [comment]
The example you can learn: [Highlight Legal Moves](https://lengyanyu258.github.io/xiangqiboardjs/examples.html#5003) and it's [source code](https://lengyanyu258.github.io/xiangqiboardjs/examples/5003.html).

**Comment by ChinYouHng** [comment]
https://user-images.githubusercontent.com/63784995/166289740-494b36ce-8c35-477e-a878-6c4ee1265560.mp4

Sorry i dont understand what to do with the [Highlight Legal Moves](https://lengyanyu258.github.io/xiangqiboardjs/examples.html#5003), what im trying to achieve is like [Config Spare Pieces](https://lengyanyu258.github.io/xiangqiboardjs/examples.html#2006)

**Comment by lengyanyu258** [comment]
Ah, I see. Sorry about my carelessness.

Maybe you can use `game.put(piece, square)` function where `game = new Xiangqi()` declared before.
Or you can use `game.load(board.fen())` function where `board = Xiangqiboard('myBoard', config)` declared before. In this case, you may meet [error](https://github.com/lengyanyu258/xiangqi.js/blob/56da10644d59401b30afe05f40cc00f4003b9c50/xiangqi.js#L157) according your move showed in video.

All these logical code should be written in the `onDrop()` function. (The example for integration showed in [Highlight Legal Moves](https://lengyanyu258.github.io/xiangqiboardjs/examples.html#5003).)

However, I haven't tested them. Maybe there are some mistakes waiting for you, but I think the solutions are something like that. Hopefully it can help you.

**Comment by ChinYouHng** [comment]
Thank you so much!
