### ISSUE TITLE
hi im a big noob :)

### ISSUE THREAD

**Issue by Omshinwa** [lengyanyu258/xiangqiboardjs#5]
http://fynmorph.free.fr/xiangqi/
https://i.imgur.com/e0vaSys.png
why arent my pieces on the board lol

**Comment by lengyanyu258** [comment]
Well, you should link CSS file to fix the problem ;-)

```html
<link rel="stylesheet" href="css/xiangqiboard-0.2.0.min.css" />
```

Also, you could use graphic pieces like this:

```js
const config = {
    pieceTheme: 'img/xiangqipieces/graphic/{piece}.svg',
    position: 'start'
}

const board = Xiangqiboard('myBoard', config);
```

See [Piece Theme String](https://lengyanyu258.github.io/xiangqiboardjs/examples.html#2004) & [Piece Theme Function](https://lengyanyu258.github.io/xiangqiboardjs/examples.html#2030).

**Comment by Omshinwa** [comment]
Lol, thank you!!

**Comment by golf-x** [comment]
I think we should close this issue as it has been resolved.
