### ISSUE TITLE
Highlight Legal Moves for pawn

### ISSUE THREAD

**Issue by Tmax9663** [lengyanyu258/xiangqiboardjs#8]
Please check the pawn legal moves after crossing the river.

**Comment by lengyanyu258** [comment]
What's wrong? Please paste the picture.
I checked again and there is no wrong for sure.

**Comment by Tmax9663** [comment]
😅Sorry,  I was wrong. 
I tested on your Highlight Legal Moves example https://lengyanyu258.github.io/xiangqiboardjs/examples.html#5003
Maybe I place ONLY a pawn in between k and K 將帥不可照面. so it does not highlight the pawn moves(left/right).
